<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Auto-generated from Guru_Crackers_2026.xlsx
     * Run: php artisan db:seed --class=ProductSeeder
     */
    public function run(): void
    {
        $products = [
            ['category' => 'One Sount Crackers', 'name' => 'Gold Lakshmi', 'unit' => '1 Pkt', 'actual_rate' => 320.00, 'net_rate' => 32.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '4" Deluxe Lakshmi', 'unit' => '1 Pkt', 'actual_rate' => 300.00, 'net_rate' => 30.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '4" Lakshmi', 'unit' => '1 Pkt', 'actual_rate' => 250.00, 'net_rate' => 25.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '3½ \'\' Lakshmi', 'unit' => '1 Pkt', 'actual_rate' => 150.00, 'net_rate' => 15.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '2¾" Kuruvi', 'unit' => '1 Pkt', 'actual_rate' => 100.00, 'net_rate' => 10.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '5" Jallikattu (Bull)', 'unit' => '1 Pkt', 'actual_rate' => 400.00, 'net_rate' => 40.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '6" Jallikattu', 'unit' => '1 Pkt', 'actual_rate' => 600.00, 'net_rate' => 60.00, 'discount_percent' => 90],
            ['category' => 'One Sount Crackers', 'name' => '2 Sound Crackers', 'unit' => '1 Pkt', 'actual_rate' => 450.00, 'net_rate' => 45.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Flower Pot Big', 'unit' => '1 Box', 'actual_rate' => 650.00, 'net_rate' => 65.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Flower Pot Asoka', 'unit' => '1 Box', 'actual_rate' => 1050.00, 'net_rate' => 105.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Color Koti', 'unit' => '1 Box', 'actual_rate' => 1800.00, 'net_rate' => 180.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Color Koti Deluxe Violet', 'unit' => '1 Box', 'actual_rate' => 7500.00, 'net_rate' => 750.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Celebration Color Koti', 'unit' => '1 Box', 'actual_rate' => 3490.00, 'net_rate' => 349.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Tower Pots', 'unit' => '1 Box', 'actual_rate' => 7200.00, 'net_rate' => 720.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'XXX Fast ( R & G )', 'unit' => '1 Box', 'actual_rate' => 3200.00, 'net_rate' => 320.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Five Colour Fauntain (5 P)', 'unit' => '1 Box', 'actual_rate' => 2800.00, 'net_rate' => 280.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Tri Colour ( 5 P)', 'unit' => '1 Box', 'actual_rate' => 2650.00, 'net_rate' => 265.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Two Colour&White House', 'unit' => '1 Box', 'actual_rate' => 1800.00, 'net_rate' => 180.00, 'discount_percent' => 90],
            ['category' => 'Flower Pots', 'name' => 'Oyolo', 'unit' => '1 Box', 'actual_rate' => 2500.00, 'net_rate' => 250.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Ground Chakkar Big', 'unit' => '1 Box', 'actual_rate' => 350.00, 'net_rate' => 35.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Ground Chakkar Special', 'unit' => '1 Box', 'actual_rate' => 750.00, 'net_rate' => 75.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Ground Chakkaram Deluxe', 'unit' => '1 Box', 'actual_rate' => 1300.00, 'net_rate' => 130.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Wire Chakkaram', 'unit' => '1 Box', 'actual_rate' => 1850.00, 'net_rate' => 185.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Whishling weel', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Win Wheel Nano', 'unit' => '1 Box', 'actual_rate' => 990.00, 'net_rate' => 99.00, 'discount_percent' => 90],
            ['category' => 'Ground Chakkaram', 'name' => 'Race Wheel', 'unit' => '1 Box', 'actual_rate' => 1300.00, 'net_rate' => 130.00, 'discount_percent' => 90],
            ['category' => 'Twinkling Star', 'name' => '1½" Twinkling Star', 'unit' => '1 Box', 'actual_rate' => 120.00, 'net_rate' => 12.00, 'discount_percent' => 90],
            ['category' => 'Twinkling Star', 'name' => '4" Twinkling Star', 'unit' => '1 Box', 'actual_rate' => 690.00, 'net_rate' => 69.00, 'discount_percent' => 90],
            ['category' => 'New Veriety', 'name' => 'Cylinder Bomb (2 Pcs)', 'unit' => '1 Box', 'actual_rate' => 2850.00, 'net_rate' => 285.00, 'discount_percent' => 90],
            ['category' => 'New Veriety', 'name' => 'Malaai Kulfi ( 3 Pcs)', 'unit' => '1 Box', 'actual_rate' => 2950.00, 'net_rate' => 295.00, 'discount_percent' => 90],
            ['category' => 'New Veriety', 'name' => 'Dragon & Peacock Touch (Mix)', 'unit' => '1 Box', 'actual_rate' => 1650.00, 'net_rate' => 165.00, 'discount_percent' => 90],
            ['category' => 'New Veriety', 'name' => 'Speed Faster R15 ( 2 Pcs)', 'unit' => '1 Box', 'actual_rate' => 2100.00, 'net_rate' => 210.00, 'discount_percent' => 90],
            ['category' => 'New Veriety', 'name' => 'Jolly Bolly Mocktail (3 Pcs)', 'unit' => '1 Box', 'actual_rate' => 5950.00, 'net_rate' => 595.00, 'discount_percent' => 90],
            ['category' => 'Bijili Crackers', 'name' => 'Red Bijili ( 100 Pcs)', 'unit' => '1 Box', 'actual_rate' => 349.00, 'net_rate' => 34.90, 'discount_percent' => 90],
            ['category' => 'Bijili Crackers', 'name' => 'Stripped Bijili ( 100 Pcs)', 'unit' => '1 Box', 'actual_rate' => 350.00, 'net_rate' => 35.00, 'discount_percent' => 90],
            ['category' => 'Bijili Crackers', 'name' => 'Peacock Bijili ( 100 Pcs )', 'unit' => '1 Box', 'actual_rate' => 490.00, 'net_rate' => 49.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Bullet Bomb', 'unit' => '1 Box', 'actual_rate' => 249.00, 'net_rate' => 24.90, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Hydro Bomb', 'unit' => '1 Box', 'actual_rate' => 750.00, 'net_rate' => 75.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Classic Bomb', 'unit' => '1 Box', 'actual_rate' => 1200.00, 'net_rate' => 120.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Dinosar Bomb', 'unit' => '1 Box', 'actual_rate' => 2000.00, 'net_rate' => 200.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Dinosour Bomb', 'unit' => '1 Pcs', 'actual_rate' => 2600.00, 'net_rate' => 260.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Small Bomb', 'unit' => '1 Pcs', 'actual_rate' => 450.00, 'net_rate' => 45.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Mediam Bomb', 'unit' => '1 Pcs', 'actual_rate' => 900.00, 'net_rate' => 90.00, 'discount_percent' => 90],
            ['category' => 'Auto Bombs', 'name' => 'Big Bomb', 'unit' => '1 Pcs', 'actual_rate' => 1800.00, 'net_rate' => 180.00, 'discount_percent' => 90],
            ['category' => 'Rockets', 'name' => 'Rocket Bomb Colour', 'unit' => '1 Box', 'actual_rate' => 780.00, 'net_rate' => 78.00, 'discount_percent' => 90],
            ['category' => 'Rockets', 'name' => 'Whistling Rocket', 'unit' => '1 Box', 'actual_rate' => 1600.00, 'net_rate' => 160.00, 'discount_percent' => 90],
            ['category' => 'Rockets', 'name' => '2 Sound Rocket', 'unit' => '1 Box', 'actual_rate' => 1850.00, 'net_rate' => 185.00, 'discount_percent' => 90],
            ['category' => 'Colour Matches', 'name' => '5 Star Matches', 'unit' => '1 Box', 'actual_rate' => 1450.00, 'net_rate' => 145.00, 'discount_percent' => 90],
            ['category' => 'Colour Matches', 'name' => 'Lap top VIP', 'unit' => '1 Box', 'actual_rate' => 2800.00, 'net_rate' => 280.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Spooky', 'unit' => '1 Box', 'actual_rate' => 3800.00, 'net_rate' => 380.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Old is Best', 'unit' => '1 Box', 'actual_rate' => 2100.00, 'net_rate' => 210.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Min mini', 'unit' => '1 Box', 'actual_rate' => 1950.00, 'net_rate' => 195.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Whizz Chakkar', 'unit' => '1 Box', 'actual_rate' => 1850.00, 'net_rate' => 185.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Cascode Candle', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Google Galata', 'unit' => '1 Box', 'actual_rate' => 1950.00, 'net_rate' => 195.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Love Dose', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Pappu Shower', 'unit' => '1 Box', 'actual_rate' => 1600.00, 'net_rate' => 160.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Barbie Sky', 'unit' => '1 Box', 'actual_rate' => 3400.00, 'net_rate' => 340.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Two Fountain', 'unit' => '1 Box', 'actual_rate' => 2000.00, 'net_rate' => 200.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => '3 in Tin (Special)', 'unit' => '1 Box', 'actual_rate' => 3400.00, 'net_rate' => 340.00, 'discount_percent' => 90],
            ['category' => 'Variety Fountain', 'name' => 'Carnival ( 2 Pcs)', 'unit' => '1 Box', 'actual_rate' => 3000.00, 'net_rate' => 300.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Vettaiyan Crackling', 'unit' => '1 Box', 'actual_rate' => 2500.00, 'net_rate' => 250.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'White Crackling', 'unit' => '1 Box', 'actual_rate' => 1950.00, 'net_rate' => 195.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'King Crackling', 'unit' => '1 Box', 'actual_rate' => 2250.00, 'net_rate' => 225.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Sky King Fountain (Mix)', 'unit' => '1 Box', 'actual_rate' => 1800.00, 'net_rate' => 180.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Red Sound & Bule ice (Mix)', 'unit' => '1 Box', 'actual_rate' => 2600.00, 'net_rate' => 260.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Carnival & Twieer Bird (Mix)', 'unit' => '1 Box', 'actual_rate' => 1850.00, 'net_rate' => 185.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Volvo Red & Gold Moments (Mix)', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Jolly Rancher', 'unit' => '1 Box', 'actual_rate' => 1650.00, 'net_rate' => 165.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Two UP', 'unit' => '1 Box', 'actual_rate' => 2100.00, 'net_rate' => 210.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Three UP', 'unit' => '1 Box', 'actual_rate' => 2300.00, 'net_rate' => 230.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Free Fire', 'unit' => '1 Box', 'actual_rate' => 2500.00, 'net_rate' => 250.00, 'discount_percent' => 90],
            ['category' => 'Crackling Fountain', 'name' => 'Red Apple & Mr. Big (Mix)', 'unit' => '1 Box', 'actual_rate' => 1700.00, 'net_rate' => 170.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Machan Shower', 'unit' => '1 Box', 'actual_rate' => 1200.00, 'net_rate' => 120.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Star Pots Shower', 'unit' => '1 Box', 'actual_rate' => 1100.00, 'net_rate' => 110.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Colour Rain Shower', 'unit' => '1 Box', 'actual_rate' => 1050.00, 'net_rate' => 105.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Golden Globe Shower', 'unit' => '1 Box', 'actual_rate' => 1200.00, 'net_rate' => 120.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Batter Shower', 'unit' => '1 Pcs', 'actual_rate' => 700.00, 'net_rate' => 70.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Peacock Feather', 'unit' => '1 Pcs', 'actual_rate' => 1200.00, 'net_rate' => 120.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Small Beacock', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Bada Beacock', 'unit' => '1 Box', 'actual_rate' => 4500.00, 'net_rate' => 450.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Magic Wips', 'unit' => '1 Box', 'actual_rate' => 1800.00, 'net_rate' => 180.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Silver Drops', 'unit' => '1 Box', 'actual_rate' => 1100.00, 'net_rate' => 110.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Cannon Ball', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Shower Variety', 'name' => 'Luxery Peacock', 'unit' => '1 Pcs', 'actual_rate' => 2000.00, 'net_rate' => 200.00, 'discount_percent' => 90],
            ['category' => 'Candle Variety', 'name' => 'Magic Gold', 'unit' => '1 Box', 'actual_rate' => 1700.00, 'net_rate' => 170.00, 'discount_percent' => 90],
            ['category' => 'Candle Variety', 'name' => 'Minions & Trix (Mix)', 'unit' => '1 Box', 'actual_rate' => 1850.00, 'net_rate' => 185.00, 'discount_percent' => 90],
            ['category' => 'Candle Variety', 'name' => 'Smoke Stick', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Candle Variety', 'name' => 'Selbe Stick', 'unit' => '1 Box', 'actual_rate' => 700.00, 'net_rate' => 70.00, 'discount_percent' => 90],
            ['category' => 'Candle Variety', 'name' => 'Jungle Music & Funtain (Mix)', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Helicopter', 'unit' => '1 Box', 'actual_rate' => 1100.00, 'net_rate' => 110.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'butter Fly', 'unit' => '1 Box', 'actual_rate' => 950.00, 'net_rate' => 95.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Banbaram', 'unit' => '1 Box', 'actual_rate' => 1000.00, 'net_rate' => 100.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Siren', 'unit' => '1 Box', 'actual_rate' => 1800.00, 'net_rate' => 180.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Photo Flash', 'unit' => '1 Box', 'actual_rate' => 750.00, 'net_rate' => 75.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Green Stone', 'unit' => '1 Box', 'actual_rate' => 1000.00, 'net_rate' => 100.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Rotation Gun Small', 'unit' => '1 Pcs', 'actual_rate' => 650.00, 'net_rate' => 65.00, 'discount_percent' => 90],
            ['category' => 'Night Variety', 'name' => 'Ring Cap', 'unit' => '1 Pcs', 'actual_rate' => 150.00, 'net_rate' => 15.00, 'discount_percent' => 90],
            ['category' => 'Guru', 'name' => 'Guru 100', 'unit' => '1 Box', 'actual_rate' => 350.00, 'net_rate' => 35.00, 'discount_percent' => 90],
            ['category' => 'Guru', 'name' => 'Guru 1', 'unit' => '1 Box', 'actual_rate' => 2000.00, 'net_rate' => 200.00, 'discount_percent' => 90],
            ['category' => 'Guru', 'name' => 'Guru 2', 'unit' => '1 Box', 'actual_rate' => 4000.00, 'net_rate' => 400.00, 'discount_percent' => 90],
            ['category' => 'Guru', 'name' => 'Guru 5', 'unit' => '1 Box', 'actual_rate' => 10000.00, 'net_rate' => 1000.00, 'discount_percent' => 90],
            ['category' => 'Guru', 'name' => 'Guru 10', 'unit' => '1 Box', 'actual_rate' => 20000.00, 'net_rate' => 2000.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '7 Shot', 'unit' => '1 Box', 'actual_rate' => 1200.00, 'net_rate' => 120.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => 'Chotta Fancy', 'unit' => '1 Box', 'actual_rate' => 400.00, 'net_rate' => 40.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '2" Single Shot', 'unit' => '1 Box', 'actual_rate' => 950.00, 'net_rate' => 95.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '2 ¾ " Single Shot', 'unit' => '1 Pcs', 'actual_rate' => 1300.00, 'net_rate' => 130.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '2" Combo Fancy (3 Pcs)', 'unit' => '1 Box', 'actual_rate' => 2900.00, 'net_rate' => 290.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '3½" Single Shot', 'unit' => '1 Pcs', 'actual_rate' => 2800.00, 'net_rate' => 280.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '3½" Wedding Special', 'unit' => '1 Pcs', 'actual_rate' => 3500.00, 'net_rate' => 350.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '4" Fancy Single Shot', 'unit' => '1 Pcs', 'actual_rate' => 3800.00, 'net_rate' => 380.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '4" Fancy (2 Pcs)', 'unit' => '1 Box', 'actual_rate' => 7000.00, 'net_rate' => 700.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '5" Fancy (2 Pcs)', 'unit' => '1 Box', 'actual_rate' => 9500.00, 'net_rate' => 950.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '6" Fancy (2 Pcs)', 'unit' => '1 Box', 'actual_rate' => 1300.00, 'net_rate' => 130.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => 'Nayakara Falls (2 Pcs)', 'unit' => '1 Pcs', 'actual_rate' => 5800.00, 'net_rate' => 580.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => '4\'\' city Jumper (SPecial)', 'unit' => '1 Box', 'actual_rate' => 8000.00, 'net_rate' => 800.00, 'discount_percent' => 90],
            ['category' => 'Single Shot Variety', 'name' => 'Penta Shot', 'unit' => '1 Box', 'actual_rate' => 1550.00, 'net_rate' => 155.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '12 Shot', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '25 Shot', 'unit' => '1 Box', 'actual_rate' => 2200.00, 'net_rate' => 220.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '30 Shot', 'unit' => '1 Box', 'actual_rate' => 4000.00, 'net_rate' => 400.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '60 Shot', 'unit' => '1 Box', 'actual_rate' => 8000.00, 'net_rate' => 800.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '100 Shot', 'unit' => '1 Box', 'actual_rate' => 14500.00, 'net_rate' => 1450.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '120 Shot', 'unit' => '1 Box', 'actual_rate' => 16000.00, 'net_rate' => 1600.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '240 Shot', 'unit' => '1 Box', 'actual_rate' => 32000.00, 'net_rate' => 3200.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '10x10 Shot', 'unit' => '1 Box', 'actual_rate' => 32000.00, 'net_rate' => 3200.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '2" Set Out', 'unit' => '1 Box', 'actual_rate' => 20000.00, 'net_rate' => 2000.00, 'discount_percent' => 90],
            ['category' => 'Multi Crackers', 'name' => '3½" Set Out', 'unit' => '1 Box', 'actual_rate' => 45000.00, 'net_rate' => 4500.00, 'discount_percent' => 90],
            ['category' => 'Giftbox', 'name' => '21 ITEM GIFT BOX', 'unit' => '1 Box', 'actual_rate' => 3000.00, 'net_rate' => 300.00, 'discount_percent' => 90],
            ['category' => 'Giftbox', 'name' => '31 ITEM GIFT BOX', 'unit' => '1 Box', 'actual_rate' => 5000.00, 'net_rate' => 500.00, 'discount_percent' => 90],
            ['category' => 'Giftbox', 'name' => '41 ITEM GIFT BOX', 'unit' => '1 Box', 'actual_rate' => 7000.00, 'net_rate' => 700.00, 'discount_percent' => 90],
            ['category' => 'Giftbox', 'name' => '51 ITEM GIFT BOX', 'unit' => '1 Box', 'actual_rate' => 9500.00, 'net_rate' => 950.00, 'discount_percent' => 90],
            ['category' => 'Giftbox', 'name' => '61 ITEM GIFT BOX', 'unit' => '1 Box', 'actual_rate' => 12000.00, 'net_rate' => 1200.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '10 CM ELECTRIC SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 180.00, 'net_rate' => 18.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '10 CM COLOUR SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 190.00, 'net_rate' => 19.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '10 CM GREEN SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 200.00, 'net_rate' => 20.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '10 CM RED SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 220.00, 'net_rate' => 22.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '12 CM ELECTRIC SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 200.00, 'net_rate' => 20.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '12 CM COLOUR SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 210.00, 'net_rate' => 21.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '12 CM GREEN SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 220.00, 'net_rate' => 22.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '12 CM RED SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 250.00, 'net_rate' => 25.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '15 CM ELECTRIC SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 380.00, 'net_rate' => 38.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '15 CM COLOUR SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 400.00, 'net_rate' => 40.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '15 CM GREEN SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 420.00, 'net_rate' => 42.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '15 CM RED SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 450.00, 'net_rate' => 45.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '30CM ELECTRIC SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 380.00, 'net_rate' => 38.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '30 CM COLOUR SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 400.00, 'net_rate' => 40.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '30 CM GREEN SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 420.00, 'net_rate' => 42.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '30 CM RED SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 450.00, 'net_rate' => 45.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '50 CM ELECTRIC SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 1500.00, 'net_rate' => 150.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => '50 CM COLOUR SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 1600.00, 'net_rate' => 160.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => 'HEARTIN SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 1950.00, 'net_rate' => 195.00, 'discount_percent' => 90],
            ['category' => 'Sparklers', 'name' => 'UMBERLA SPARKLERS', 'unit' => '1 Box', 'actual_rate' => 1700.00, 'net_rate' => 170.00, 'discount_percent' => 90],
            ['category' => 'Combo Offer', 'name' => 'KIDS COMBO', 'unit' => '1 Box', 'actual_rate' => 3000.00, 'net_rate' => 3000.00, 'discount_percent' => 0],
            ['category' => 'Combo Offer', 'name' => 'BACHELOR COMBO', 'unit' => '1 Box', 'actual_rate' => 5000.00, 'net_rate' => 5000.00, 'discount_percent' => 0],
            ['category' => 'Combo Offer', 'name' => 'FAMILY COMBO', 'unit' => '1 Box', 'actual_rate' => 10000.00, 'net_rate' => 10000.00, 'discount_percent' => 0],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
